apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
